# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - resilient

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "composer.json"

      - name: Get Composer vendor directory
        run: |
          composer config vendor-dir --absolute
          composer config cache-dir --absolute

      - name: Setup Composer Dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist --optimize-autoloader"

      - name: Install zip
        uses: montudor/action-zip@v1.0.0

      - name: List current files
        run: ls -a
        
      - name: List vendor folder
        run: ls vendor -a

      - name: Create a list of files to deploy
        run: bin/deploy

      - name: Upload list for records
        uses: actions/upload-artifact@v3
        with:
          name: filelist
          path: deployed.txt

      - name: Compress the listed files
        run: |
          zip -r -@ app.zip $(cat deployed.txt) vendor

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "resilient"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_44E30365F5244A7787CE7307AE02AA8E }}
          package: app.zip
